version: '0.0.{build}'

image: Visual Studio 2017

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

clone_depth: 1

pull_requests:  
  do_not_increment_build_number: true

branches:  
  only:
  - master

nuget:  
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  # Install repo specific stuff here

before_build:
  # Display .NET Core version
  - cmd: dotnet --version

build_script:
  - cmd: dotnet publish ./CodeStreamAspNetCoreApiStarter.csproj -c Release -f netcoreapp2.1

test: off  

artifacts:
 - path: '\bin\Release\netcoreapp2.1\publish'
   name: WebSite

deploy:
- provider: WebDeploy
  server: https://CodeStreamAspNetCoreApiStarter.scm.azurewebsites.net:443/msdeploy.axd?site=CodeStreamAspNetCoreApiStarter
  website: CodeStreamAspNetCoreApiStarter
  username: $CodeStreamAspNetCoreApiStarter
  password:
    secure: euBkKta2Lqk1xLtga+c1qn0vo34X2lAwTY2c2AwLbkdsquwBHmulsVwFLZ3TeLMEERZZh6DOZb5dgCvPnnbmSg==
  remove_files: true
  app_offline: true
  artifact: WebSite